QuanLyNhanSu/Controllers/QLPhongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyNhanSu.Models;

namespace QuanLyNhanSu.Controllers
{
    public class QLPhongsController : Controller
    {
        private DBContext db = new DBContext();

        // GET: QLPhongs
        public ActionResult Index()
        {
            return View(db.tblPhongs.ToList());
        }

        // GET: QLPhongs/Details/5
        public ActionResult Details(string id)
        {
           if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPhong tblPhong = db.tblPhongs.Find(id);
            if (tblPhong == null)
            {
                return HttpNotFound();
            }
            /*var NVTP = db.tblThongTinNVs.Where(x => x.MaPhong == id).ToList();
            if (NVTP == null)
            {
                return HttpNotFound();
            }*/
            return View(tblPhong);
        }

        // GET: QLPhongs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QLPhongs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaPhong,TenPhong,TenTruongPhong,DienThoaiPhong")] tblPhong tblPhong)
        {
            if (ModelState.IsValid)
            {
                db.tblPhongs.Add(tblPhong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblPhong);
        }

        // GET: QLPhongs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPhong tblPhong = db.tblPhongs.Find(id);
            if (tblPhong == null)
            {
                return HttpNotFound();
            }
            return View(tblPhong);
        }

        // POST: QLPhongs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaPhong,TenPhong,TenTruongPhong,DienThoaiPhong")] tblPhong tblPhong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblPhong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblPhong);
        }

        // GET: QLPhongs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPhong tblPhong = db.tblPhongs.Find(id);
            if (tblPhong == null)
            {
                return HttpNotFound();
            }
            return View(tblPhong);
        }

        // POST: QLPhongs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tblPhong tblPhong = db.tblPhongs.Find(id);
            db.tblPhongs.Remove(tblPhong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

QuanLyNhanSu/Views/QLPhongs/Create.cshtml
@model QuanLyNhanSu.Models.tblPhong

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Thêm phòng/ban</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal px-md-4">
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <a>Mã phòng</a>
            <div class="col-md-5 pb-2">
                @Html.EditorFor(model => model.MaPhong, new { htmlAttributes = new { @class = "form-control pb-1" } })
                @Html.ValidationMessageFor(model => model.MaPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group pb-2">
            @Html.LabelFor(model => model.TenPhong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.TenPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group pb-2">
            @Html.LabelFor(model => model.TenTruongPhong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.TenTruongPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTruongPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group pb-2">
            @Html.LabelFor(model => model.DienThoaiPhong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.DienThoaiPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoaiPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2">
                <input type="submit" value="Lưu lại" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="px-md-4">
    @Html.ActionLink("Back to List", "Index")
</div>

QuanLyNhanSu/Views/QLPhongs/Delete.cshtml
@model QuanLyNhanSu.Models.tblPhong

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Xóa phòng/ban</h2>

<div class=" d-flex justify-content-center align-content-center pt-5">
    <dl class="dl-horizontal">
        <dt>
            Phòng/ban
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenPhong)
        </dd>

        <dt>
            Trưởng phòng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTruongPhong)
        </dd>

        <dt>
            Số điện thoại 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoaiPhong)
        </dd>
        <dd>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                        <div class="form-actions">
                            <input type="submit" value="Xác nhận xóa" class="btn btn-danger" /> &nbsp;
                            @Html.ActionLink("Quay lại danh sách", "Index",null, new { @class="btn btn-primary"})
                        </div>}
        </dd>
    </dl>
</div>

QuanLyNhanSu/Views/QLPhongs/Details.cshtml
@model QuanLyNhanSu.Models.tblPhong
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2" style="text-align:center">Chi tiết @Html.DisplayFor(model=>model.TenPhong)</h2>

<div class="d-flex justify-content-center">
    <dl class="dl-horizontal">
        <dt>
            Tên phòng/ban
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenPhong)
        </dd>

        <dt>
            Trưởng phòng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTruongPhong)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoaiPhong)
        </dd>
        <dd>
            <p>
                <a href="@Url.Action("Index", "QLPhongs")" class="btn btn-success">
                    Quay lại
                </a>
            </p>
        </dd>
    </dl>
</div>
@*<div>
    <h4>Danh sách nhân viên phòng</h4>
    <table class="table">
        <tr>
            <th>Mã nhân viên</th>
            <th>Tên nhân viên</th>
            <th>Chức vụ</th>
        </tr>
        
        <tr>
            <th>
                @Html.DisplayFor(model => model.tblThongTinNVs.)
             </th>
            <th>
                @Html.DisplayFor(model => model.TenNV)
            </th>
            <th>
                @Html.DisplayFor(model=>model.ChucVu)
            </th>
        </tr>
    </table>
</div>*@

QuanLyNhanSu/Views/QLPhongs/Edit.cshtml
@model QuanLyNhanSu.Models.tblPhong

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Chỉnh sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal px-md-5 pt-3">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaPhong)

        <div class="form-group d-flex pb-5">
            @Html.LabelFor(model => model.TenPhong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.TenPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pb-5">
            @Html.LabelFor(model => model.TenTruongPhong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.TenTruongPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTruongPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pb-5">
            @Html.LabelFor(model => model.DienThoaiPhong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.DienThoaiPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoaiPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex">
            <div>
                <input type="submit" value="Lưu lại" class="btn btn-success" />
            </div>
            <div class="ml-2">
                @Html.ActionLink("Danh sách", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}
<style>
    .ml-2
    {
        margin-left: 10px
    }
</style>

QuanLyNhanSu/Views/QLPhongs/Index.cshtml
@model IEnumerable<QuanLyNhanSu.Models.tblPhong>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2" style="text-align:center">Danh Sách phòng ban</h2>
<p class="px-md-5">
    @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-success" })
</p>
<form class="px-md-5">
    <table class="table">
        <tr>
            <th>
                Tên Phòng/ban
            </th>
            <th>
                Trưởng phòng
            </th>
            <th>
                Số điện thoại
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TenPhong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenTruongPhong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DienThoaiPhong)
                </td>
                <td>
                    <a href="@Url.Action("Edit","QLPhongs", new { id = item.MaPhong})">
                        <i class="fa-sharp fa-regular fa-pen-to-square"></i>
                    </a>&nbsp;
                    <a href="@Url.Action("Details","QLPhongs", new { id = item.MaPhong})">
                        <i class="fa-sharp fa-solid fa-calendar-week"></i>
                    </a>&nbsp;
                    <a href="@Url.Action("Delete","QLPhongs", new { id = item.MaPhong})">
                        <i class="fa-sharp fa-solid fa-trash"></i>
                    </a>
                </td>
            </tr>
        }

    </table>
</form>