QuanLyNhanSu/Controllers/ChamCongController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExcelDataReader;
using iTextSharp.text;
using OfficeOpenXml;
using PagedList;
using QuanLyNhanSu.Models;
namespace QuanLyNhanSu.Controllers
{
    public class ChamCongController : Controller
    {
        private DBContext db = new DBContext();
        public DbSet<tblChamCongs> tblChamCongs { get; set; }

        // GET: ChamCong
        public ActionResult Index(string name, int page = 1)
        {
            page = page < 1 ? 1 : page;
            int pagesize = 10;
            var tblChamCong = db.tblChamCongs.OrderByDescending(x => x.Ngay).ThenBy(x => x.TenNV);
            return View(tblChamCong.ToPagedList(page, pagesize));
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase excelFile)
        {
            if (excelFile != null && excelFile.ContentLength > 0 &&
        (Path.GetExtension(excelFile.FileName) == ".xls" || Path.GetExtension(excelFile.FileName) == ".xlsx"))
            {
                try
                {
                    // Create a stream for the Excel file
                    Stream stream = excelFile.InputStream;
                    IExcelDataReader reader = null;

                    // Read the Excel file with either OpenXML or ClosedXML
                    if (Path.GetExtension(excelFile.FileName) == ".xls")
                    {
                        reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    }
                    else if (Path.GetExtension(excelFile.FileName) == ".xlsx")
                    {
                        reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }

                    // Read the data from the Excel file
                    DataSet result = reader.AsDataSet();

                    // Loop through each sheet in the Excel file and read the data
                    
                   
                    foreach (DataTable table in result.Tables)
                    {
                        // Loop through each row in the sheet
                        for (int i = 1; i < table.Rows.Count; i++)
                        {
                            // Create a new TimeLog object and set its properties
                            var cc = new tblChamCongs();                            
                            cc.MaNV = table?.Rows[i][0].ToString();
                            cc.TenNV = table?.Rows[i][1].ToString();
                           
                            string dateString = table?.Rows[i][2].ToString();
                            if (DateTime.TryParse(dateString, out DateTime dateValue))
                            {
                                cc.Ngay = dateValue;
                                
                            }
                            else
                            {
                                ViewBag.Message = "Ngày không đúng định dạng";
                            }
                            string timeString = table?.Rows[i][3].ToString();
                            timeString = timeString.Replace("SA", "AM").Replace("CH", "PM");
                            TimeSpan timeSpan = DateTime.ParseExact(timeString, "dd/MM/yyyy h:mm:ss tt", CultureInfo.InvariantCulture).TimeOfDay;
                            cc.ThoiGianVao = timeSpan;
                            string timeString1 = table?.Rows[i][4].ToString();
                            timeString1 = timeString1.Replace("SA", "AM").Replace("CH", "PM");
                            TimeSpan timeSpan1 = DateTime.ParseExact(timeString1, "dd/MM/yyyy h:mm:ss tt", CultureInfo.InvariantCulture).TimeOfDay;
                            cc.ThoiGianRa = timeSpan1;

                            cc.TrangThai = table?.Rows[i][5].ToString();
                            //kiem tra trung lap thong tin
                            var chamcongs = db.tblChamCongs.Where(a => a.MaNV == cc.MaNV && a.Ngay == cc.Ngay);
                            if (chamcongs.Count() > 0)
                            {
                                db.SaveChanges();
                            }
                            else {
                                db.tblChamCongs.Add(cc);
                                db.SaveChanges();
                            }
                            
                        }

                    }
                    



                    // Close the Excel reader and stream
                    reader.Close();
                    stream.Close();

                    // Return success message
                    ViewBag.Message = "Tải lên thành công";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    
                    // Return error message
                    ViewBag.Message = "Lỗi: " + ex.Message;
                    return View();
                }
            }
            else
            {
                // Return error message if file is not Excel file
                ViewBag.Message = "Hãy chọn tệp Excel";
                return View();
            }
        }
        // GET: ChamCong/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblChamCongs tblChamCong = db.tblChamCongs.Find(id);
            if (tblChamCong == null)
            {
                return HttpNotFound();
            }
            return View(tblChamCong);
        }

        // GET: ChamCong/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChamCong/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,MaNV,TenNV,Ngay,ThoiGianVao,ThoiGianRa,TrangThai")] tblChamCongs tblChamCong)
        {

            if (ModelState.IsValid)
            {

                db.tblChamCongs.Add(tblChamCong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblChamCong);
        }

        // GET: ChamCong/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblChamCongs tblChamCong = db.tblChamCongs.Find(id);
            if (tblChamCong == null)
            {
                return HttpNotFound();
            }
            return View(tblChamCong);
        }

        // POST: ChamCong/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,MaNV,TenNV,Ngay,ThoiGianVao,ThoiGianRa,TrangThai")] tblChamCongs tblChamCong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblChamCong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblChamCong);
        }

        // GET: ChamCong/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblChamCongs tblChamCong = db.tblChamCongs.Find(id);
            if (tblChamCong == null)
            {
                return HttpNotFound();
            }
            return View(tblChamCong);
        }

        // POST: ChamCong/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblChamCongs tblChamCong = db.tblChamCongs.Find(id);
            db.tblChamCongs.Remove(tblChamCong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
       
        public ActionResult ChamCongNhanVien()
        {
            
            string ma = (string)Session["MaNV"];
            var ttcc = db.tblChamCongs.Where(x => x.MaNV == ma).OrderByDescending(x => x.Ngay);
            return View(ttcc);
        }
        public ActionResult NhanVienChamCong()
        {
            /*bool isSunday = DateTime.Today.DayOfWeek == DayOfWeek.Sunday;

            if (isSunday)
            {
                ViewBag.Message = "Hôm nay là chủ nhật, không thể chấm công";
                return View();
            }
            if (DateTime.Now.Hour >= 20 || DateTime.Now.Hour < 8)
            {
                ViewBag.Message = "Không phải giờ hành chính của công ty, không thể chấm công";
                return View();
            }*/
            return View();
        }
        [HttpPost]
        public ActionResult NhanVienChamCong(tblChamCongs cc)
        {
            string ma = (string)Session["MaNV"];
                cc.MaNV = ma;
                if (ModelState.IsValid)
                {
                    cc.MaNV = ma;
                    cc.TenNV = db.tblThongTinNVs.Find(ma).TenNV;
                    cc.Ngay = DateTime.Now;
                    string timeString = Request.Form["timeBox"];
                    cc.ThoiGianVao = DateTime.ParseExact(timeString, "h:mm:ss tt", CultureInfo.InvariantCulture).TimeOfDay;
                    cc.ThoiGianRa = DateTime.ParseExact(Request.Form["timeBox1"], "h:mm:ss tt", CultureInfo.InvariantCulture).TimeOfDay;

QuanLyNhanSu/Views/ChamCong/ChamCongNhanVien.cshtml
@model IEnumerable<QuanLyNhanSu.Models.tblChamCongs>
@{
    ViewBag.Title = "Thông tin chấm công";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<h2 class="headerh2">Bảng chấm công</h2>
<form class="px-md-4 w-auto">
    <table class="table">
        <tr class="text-danger">
            <th>
                Ngày
            </th>
            <th>
                Giờ vào
            </th>
            <th>
                Giờ ra
            </th>
            <th>
                Trạng thái
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @Html.DisplayFor(modelItem => item.Ngay)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.ThoiGianVao)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.ThoiGianRa)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.TrangThai)
                </th>
            </tr>
        }
    </table>
</form>

QuanLyNhanSu/Views/ChamCong/Create.cshtml
@model QuanLyNhanSu.Models.tblChamCongs

@{
    ViewBag.Title = "LuuChamCong";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2 class="headerh2">Chấm công</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.MaNV)
        @Html.TextBoxFor(m => m.MaNV, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.TenNV)
        @Html.TextBoxFor(m => m.TenNV, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ThoiGianVao)
        @Html.TextBoxFor(m => m.ThoiGianVao, new { @class = "form-control", @readonly = true })
        <button type="button" class="btn btn-primary" onclick="chamCong('gioVao')">Giờ vào</button>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ThoiGianRa)
        @Html.TextBoxFor(m => m.ThoiGianRa, new { @class = "form-control", @readonly = true })
        <button type="button" class="btn btn-primary" onclick="chamCong('gioRa')">Giờ ra</button>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-success">Lưu</button>
    </div>
}


<script>
    function chamCong(type) {
        var now = new Date();
        var hours = now.getHours();
        var minutes = now.getMinutes();
        var seconds = now.getSeconds();
        var timeStr = hours + ":" + minutes + ":" + seconds;

        if (type === "gioVao") {
            $("#GioVao").val(timeStr);
        } else {
            $("#GioRa").val(timeStr);
        }
    }
</script>

QuanLyNhanSu/Views/ChamCong/Delete.cshtml
@model QuanLyNhanSu.Models.tblChamCongs

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Xóa</h2>
<div class="d-flex justify-content-center">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiGianVao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGianVao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiGianRa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGianRa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>
        <dd>
            @using (Html.BeginForm())
            {
        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-outline-danger" />
                            @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-primary" })
                        </div>}
        </dd>
    </dl>
</div>

QuanLyNhanSu/Views/ChamCong/Details.cshtml
@model QuanLyNhanSu.Models.tblChamCongs

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblChamCong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiGianVao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGianVao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiGianRa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGianRa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QuanLyNhanSu/Views/ChamCong/Edit.cshtml
@model QuanLyNhanSu.Models.tblChamCongs

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Chỉnh sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="px-md-4">
    <div class="form-horizontal pt-3">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group d-flex">
            @Html.LabelFor(model => model.MaNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pt-2">
            @Html.LabelFor(model => model.TenNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pt-2">
            @Html.LabelFor(model => model.Ngay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Ngay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pt-2">
            @Html.LabelFor(model => model.ThoiGianVao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.ThoiGianVao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThoiGianVao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pt-2">
            @Html.LabelFor(model => model.ThoiGianRa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.ThoiGianRa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThoiGianRa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pt-2">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>


    </div>
    <div class="form-group pt-3">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu lại" class="btn btn-success" /> &nbsp;
            @Html.ActionLink("Danh sách", "Index", null, new { @class = "btn btn-primary" })
        </div>
        
    </div>
</div>

}

QuanLyNhanSu/Views/ChamCong/Index.cshtml
@model PagedList.IPagedList<QuanLyNhanSu.Models.tblChamCongs>
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Danh sách chấm công</h2>
@using (Html.BeginForm("Index", "ChamCong", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group d-flex px-md-4 pb-2">
        <div class="input-group w-50">
            <label class="input-group-btn">
                <span class="btn btn-primary">
                    Chọn tệp&hellip; <input type="file" style="display: none;" name="excelFile" id="exampleInputFile">
                </span>
            </label>
            <input type="text" class="form-control" readonly  placeholder="Chỉ hỗ trợ tệp .xls, .xlsx">
        </div>
        <button type="submit" class="btn btn-primary">Tải lên</button>
    </div>

    <div class="alert alert-info" role="alert" style="display:none;"> </div>
    <div class="px-md-5"><p class="text-danger">@ViewBag.Message</p></div>
}
<form class="px-md-4">
    <table class="table">
        <tr>
            <th>
                Mã nhân viên
            </th>
            <th>
                Họ và tên
            </th>
            <th>
                Ngày
            </th>
            <th>
                Thời gian vào
            </th>
            <th>
                Thời gian ra
            </th>
            <th>
                Trạng thái
            </th>
            <th></th>
        </tr>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaNV)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenNV)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ngay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ThoiGianVao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ThoiGianRa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TrangThai)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID })|
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }
        }

    </table>
</form>
<div class="pagination px-md-4 pt-2">
    @if (Model != null)
    {
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, @class = "pagination" }))
    }
</div>
<script>
    $('input[type="file"]').change(function (e) {
        var fileName = e.target.files[0].name;
        $('input[type="text"]').val(fileName);
        $('.alert-info').hide();
        $('.help-block').hide();
    });

    localStorage.removeItem("noti")
</script>

QuanLyNhanSu/Views/ChamCong/NhanVienChamCong.cshtml
@model QuanLyNhanSu.Models.tblChamCongs
@{ ViewBag.Title = "NhanVienChamCong";
                Layout = "~/Views/Shared/_Layout2.cshtml"; }
<h2 class="headerh2">Chấm công</h2>
<div class="d-flex justify-content-center">
    @if (!string.IsNullOrEmpty(ViewBag.Message))
    {

        <h3 class="text-danger px-md-5">@ViewBag.Message</h3> 
    }
     else
    {
    using (Html.BeginForm("NhanVienChamCong", "ChamCong", FormMethod.Post))
    {
    <div class="px-md-5">
        <input type="button" value="Giờ vào" onclick="getCurrentTime()" />
        <input type="text" id="timeBox" name="timeBox" />
        <input type="button" value="Giờ Ra" onclick="getCurrentTime1()" />
        <input type="text" id="timeBox1" name="timeBox1" />
        <input type="submit" value="Chấm công" />
    </div>}
}
</div>

<div class="px-md-5">
    <table class="table">
        <tr>
            <th>
                Ngày
            </th>
            <th>
                Giờ vào
            </th>
            <th>
                Giờ ra
            </th>
            <th>
                Trạng thái
            </th>
        </tr>
        <tr>
            @if (Model != null)
            {
                <th>
                    @Model.Ngay
                </th>
                <th>
                    @Model.ThoiGianVao
                </th>
                <th>
                     @Model.ThoiGianRa
                </th>
                <th>
                    @Model.TrangThai
                </th>
             }
        </tr>
    </table>
</div>

<script>
    function getCurrentTime() {
        var now = new Date();
        var hour = now.getHours();
        var minute = now.getMinutes();
        var second = now.getSeconds();
        if (hour >= 0 && hour < 12) {
            var time = hour + ":" + minute + ":" + second + " " + "AM";
        }
        else {
            var time = hour - 12 + ":" + minute + ":" + second + " " + "PM";
        }

        document.getElementById("timeBox").value = time;
    }
    function getCurrentTime1() {
        var now = new Date();
        var hour = now.getHours();
        var minute = now.getMinutes();
        var second = now.getSeconds();
        if (hour >= 0 && hour < 12) {
            var time = hour + ":" + minute + ":" + second + " " + "AM";
        }
        else {
            var time = hour - 12 + ":" + minute + ":" + second + " " + "PM";
        }
        document.getElementById("timeBox1").value = time;
    }
</script>