QuanLyNhanSu/Areas/Admin/Controllers/QLTaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyNhanSu.Models;
using PagedList;
namespace QuanLyNhanSu.Areas.Admin.Controllers
{
    public class QLTaiKhoanController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Admin/QLTaiKhoan
        public ActionResult Index(string name, int page = 1)
        {
            page = page < 1 ? 1 : page;
            int pagesize = 3;
            var tks = db.tblUsers.OrderBy(x => x.IDUser);
            if (!string.IsNullOrEmpty(name))
            {
                tks = db.tblUsers.Where(x => x.UserName.Contains(name)).OrderBy(x => x.UserName);
            }
            return View(tks.ToPagedList(page,pagesize));
        }

        // GET: Admin/QLTaiKhoan/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUser tblUser = db.tblUsers.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // GET: Admin/QLTaiKhoan/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/QLTaiKhoan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDUser,UserName,Password,Quyen,MaNV,TenNV,TrangThai")] tblUser tblUser)
        {
            if (ModelState.IsValid)
            {
                db.tblUsers.Add(tblUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblUser);
        }

        // GET: Admin/QLTaiKhoan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUser tblUser = db.tblUsers.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // POST: Admin/QLTaiKhoan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDUser,UserName,Password,Quyen,MaNV,TenNV,TrangThai")] tblUser tblUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblUser);
        }

        // GET: Admin/QLTaiKhoan/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUser tblUser = db.tblUsers.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // POST: Admin/QLTaiKhoan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblUser tblUser = db.tblUsers.Find(id);
            db.tblUsers.Remove(tblUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyNhanSu/Areas/Admin/Views/QLTaiKhoan/Create.cshtml
@model QuanLyNhanSu.Models.tblUser

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Thêm mới tài khoản</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal px-md-5">
    
        <div class="form-group">
            Tên tài khoản
            <div class="col-md-5">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Mật khẩu
            <div class="col-md-5">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Quyền
            <div class="col-md-5">
                @Html.EditorFor(model => model.Quyen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quyen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Mã nhân viên
            <div class="col-md-5">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Tên nhân viên
            <div class="col-md-5">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Trạng thái
            <div class="col-md-5">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TrangThai)
                    @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group pt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu lại" class="btn btn-success" />
                @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

QuanLyNhanSu/Areas/Admin/Views/QLTaiKhoan/Delete.cshtml
@model QuanLyNhanSu.Models.tblUser

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Xóa tài khoản</h2>
<div class="d-flex justify-content-center">
    <dl class="dl-horizontal">
        <dt>
            Tên tài khoản
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            Mật khẩu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            Quyền
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quyen)
        </dd>

        <dt>
            Mã nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNV)
        </dd>

        <dt>
            Tên nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            Trạng thái
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>
        <dd class="pt-3">
            @using (Html.BeginForm())
            {
        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Xác nhận xóa" class="btn btn-danger" /> &nbsp;
                            @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-primary" })
                        </div>}
        </dd>
    </dl>

    
</div>

QuanLyNhanSu/Areas/Admin/Views/QLTaiKhoan/Details.cshtml
@model QuanLyNhanSu.Models.tblUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quyen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quyen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.IDUser }) |
    @Html.ActionLink("Quay lại danh sách", "Index",null,new { @class = "btn btn-primary"})
</p>

QuanLyNhanSu/Areas/Admin/Views/QLTaiKhoan/Edit.cshtml
@model QuanLyNhanSu.Models.tblUser

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Sửa thông tin tài khoản</h2>
<div class="px-md-5">
    @using (Html.BeginForm())
    {
@Html.AntiForgeryToken()

                <div>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IDUser)
                    <div class="dl-horizontal">
                        Tên tài khoản
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        Mật khẩu
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        Quyền
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.Quyen, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Quyen, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        Mã nhân viên
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        Tên nhân viên
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group pb-2">
                        Trạng thái
                        <div class="col-md-5">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.TrangThai)
                                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group pt-2">
                        <div class="col-md-offset-2 col-md-5">
                            <input type="submit" value="Lưu lại" class="btn btn-success" /> &nbsp;
                                @Html.ActionLink("Quay lại danh sách", "Index",null,new {@class="btn btn-primary" })
                        </div>
                    </div>
                </div>
      }
</div>

QuanLyNhanSu/Areas/Admin/Views/QLTaiKhoan/Index.cshtml
@model PagedList.IPagedList<QuanLyNhanSu.Models.tblUser>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2" style="text-align:center">Danh sách tài khoản</h2>

<p class="px-md-4">
    @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-success" })
</p>
<form asp-action="Index" method="get" class="form-inline px-md-4 pt-2" style="width:50%; display:flex">
    <input class="form-control" name="name" placeholder="Nhập tên tài khoản..." type="text">
    <button class="btn btn-primary" type="submit">
        <i class="fas fa-search"></i>
    </button>
</form>
<form class="px-md-4 pt-4">
    <table class="table">
        <tr>
            <th>
                Tên đăng nhập
            </th>
            <th>
                Mật khẩu
            </th>
            <th>
                Quyền
            </th>
            <th>
                Mã nhân viên
            </th>
            <th>
                Tên nhân viên
            </th>
            <th>
                Trạng thái
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quyen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TrangThai)
                </td>
                <td>
                    <a href="@Url.Action("Edit","QLTaiKhoan", new { id = item.IDUser})">
                        <i class="fa-sharp fa-regular fa-pen-to-square"></i>
                    </a>&nbsp;
                    <a href="@Url.Action("Delete","QLTaiKhoan", new { id = item.IDUser})">
                        <i class="fa-sharp fa-solid fa-trash"></i>
                    </a>
                </td>
            </tr>
        }

    </table>
</form>
<div class="pagination px-md-4 pt-2">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, @class = "pagination" }))
</div>
<style>

    .pagination {
        display: flex;
    }

        .pagination a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
            border: 1px solid #ddd;
        }

        .pagination li.active {
            background-color: #4CAF50;
            color: white;
            border: 1px solid #4CAF50;
        }

        .pagination a:hover:not(.active) {
            background-color: #ddd;
        }

        .pagination a:first-child {
            border-top-left-radius: 5px;
            border-bottom-left-radius: 5px;
        }

        .pagination a:last-child {
            border-top-right-radius: 5px;
            border-bottom-right-radius: 5px;
        }
</style>