QuanLyNhanSu/Controllers/QLLuongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;
using iTextSharp.text;
using iTextSharp.text.pdf;
using PagedList;
using QuanLyNhanSu.Models;


namespace QuanLyNhanSu.Controllers
{
    public class QLLuongsController : Controller
    {
        private DBContext db = new DBContext();


        // GET: QLLuongs
        public ActionResult Index(string searchName, int? searchMonth, int page = 1)
        {
            var tblLuongs = db.tblLuongs.Include(t => t.tblPhuCap).Include(t => t.tblThongTinNV).Include(t => t.tblThuong).OrderBy(b => b.MaNV);
            page = page < 1 ? 1 : page;
            int pagesize = 5;
            if (!string.IsNullOrEmpty(searchName))
            {
                tblLuongs = db.tblLuongs.Include(t => t.tblPhuCap).Include(t => t.tblThongTinNV).Include(t => t.tblThuong).Where(l => l.tblThongTinNV.TenNV.Contains(searchName)).OrderBy(b => b.MaNV);
            }

            if (searchMonth.HasValue)
            {
                tblLuongs = db.tblLuongs.Where(s => s.Thang == searchMonth.Value).OrderBy(x => x.MaNV);
            }
            if (!string.IsNullOrEmpty(searchName) && searchMonth.HasValue)
            {
                tblLuongs = db.tblLuongs.Include(t => t.tblPhuCap).Include(t => t.tblThongTinNV).Include(t => t.tblThuong).Where(l => l.tblThongTinNV.TenNV.Contains(searchName) && l.Thang == searchMonth.Value).OrderBy(x => x.MaNV);
            }
            return View(tblLuongs.ToPagedList(page, pagesize));
        }

        // GET: QLLuongs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLuong tblLuong = db.tblLuongs.Find(id);
            if (tblLuong == null)
            {
                return HttpNotFound();
            }
            return View(tblLuong);
        }

        // GET: QLLuongs/Create
        public ActionResult Create()
        {
            ViewBag.MaHSL = new SelectList(db.tblHSLs, "MaHSL", "HSL");
            ViewBag.MaPhuCap = new SelectList(db.tblPhuCaps, "MaPhuCap", "MaPhuCap");
            ViewBag.MaNV = new SelectList(db.tblThongTinNVs, "MaNV", "TenNV");
            ViewBag.MaThuong = new SelectList(db.tblThuongs, "MaThuong", "MaThuong");

            return View();
        }

        // POST: QLLuongs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaLuong,Thang,MaNV,SoNgayLamViec,SoGioLamViec,MaHSL,MaThuong,MaPhuCap,TienPhat,TamUng")] tblLuong tblLuong)
        {
            if (ModelState.IsValid)
            {
                var listngaynghi = db.tblNghiPhep.Where(x => x.MaNV == tblLuong.MaNV && x.Duyet == true).ToList();
                int ngaynghi = 0;
                foreach (var item in listngaynghi)
                {
                    TimeSpan t = item.NgayKetThuc.Value - item.NgayBatDau.Value;
                    int songay = Convert.ToInt32(t.TotalDays);
                    ngaynghi += songay;
                }
                tblLuong.SoNgayLamViec += ngaynghi;
                db.tblLuongs.Add(tblLuong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaPhuCap = new SelectList(db.tblPhuCaps, "MaPhuCap", "TienPhuCap", tblLuong.MaPhuCap);
            ViewBag.MaNV = new SelectList(db.tblThongTinNVs, "MaNV", "TenNV", tblLuong.MaNV);
            ViewBag.MaThuong = new SelectList(db.tblThuongs, "MaThuong", "TienThuong", tblLuong.MaThuong);
            return View(tblLuong);
        }

        // GET: QLLuongs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLuong tblLuong = db.tblLuongs.Find(id);
            if (tblLuong == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaPhuCap = new SelectList(db.tblPhuCaps, "MaPhuCap", "TienPhuCap", tblLuong.MaPhuCap);
            ViewBag.MaNV = new SelectList(db.tblThongTinNVs, "MaNV", "TenNV", tblLuong.MaNV);
            ViewBag.MaThuong = new SelectList(db.tblThuongs, "MaThuong", "LoaiThuong", tblLuong.MaThuong);
            return View(tblLuong);
        }

        // POST: QLLuongs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLuong,Thang,MaNV,SoNgayLamViec,SoGioLamViec,HSL,MaThuong,MaPhuCap,TienPhat,TamUng")] tblLuong tblLuong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblLuong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaPhuCap = new SelectList(db.tblPhuCaps, "MaPhuCap", "MaPhuCap", tblLuong.MaPhuCap);
            ViewBag.MaNV = new SelectList(db.tblThongTinNVs, "MaNV", "TenNV", tblLuong.MaNV);
            ViewBag.MaThuong = new SelectList(db.tblThuongs, "MaThuong", "MaThuong", tblLuong.MaThuong);
            return View(tblLuong);
        }

        // GET: QLLuongs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLuong tblLuong = db.tblLuongs.Find(id);
            if (tblLuong == null)
            {
                return HttpNotFound();
            }
            return View(tblLuong);
        }

        // POST: QLLuongs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tblLuong tblLuong = db.tblLuongs.Find(id);
            db.tblLuongs.Remove(tblLuong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public FileResult ExportToExcel(int? month)
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[11] { new DataColumn("Mã lương"),
                                                     new DataColumn("ID"),
                                                     new DataColumn("Họ và tên"),
                                                     new DataColumn("Tháng"),

                                                     new DataColumn("Số ngày làm việc"),
                                                     new DataColumn("Số giờ làm việc"),
                                                     new DataColumn("Mã hệ số lương"),
                                                     new DataColumn("Mã phụ cấp"),
                                                     new DataColumn("Tiền phạt"),
                                                     new DataColumn("Tạm ứng"),
                                                     new DataColumn("Tổng lương"),});

            var insuranceCertificate = from tblLuong in db.tblLuongs
                                       join tblThongTinNV in db.tblThongTinNVs on tblLuong.MaNV equals tblThongTinNV.MaNV
                                       where tblLuong.Thang == month
                                       select new { tblLuong, tblThongTinNV };

            foreach (var insurance in insuranceCertificate)
            {
                dt.Rows.Add(insurance.tblLuong.MaLuong, insurance.tblThongTinNV.MaNV, insurance.tblThongTinNV.TenNV, insurance.tblLuong.Thang, insurance.tblLuong.SoNgayLamViec,
                    insurance.tblLuong.SoGioLamViec, insurance.tblLuong.MaHSL, insurance.tblLuong.MaPhuCap, insurance.tblLuong.TienPhat, insurance.tblLuong.TamUng, insurance.tblLuong.TongLuong());
            }

            using (XLWorkbook wb = new XLWorkbook()) //Install ClosedXml from Nuget for XLWorkbook  
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream()) //using System.IO;  
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "DanhSachLuong.xlsx");
                }
            }
        }
        public ActionResult DownloadPDF(string id)
        {
            // Lấy thông tin lương của nhân viên với ID được truyền vào
            tblLuong tblLuong = db.tblLuongs.Find(id);

            // Tạo file PDF
            MemoryStream stream = new MemoryStream();
            Document pdfDoc = new Document(PageSize.A4, 50, 50, 25, 25);
            PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
            BaseFont timesNewRoman = BaseFont.CreateFont("C:/Users/Admin/Desktop/TTTN/QuanLyNhanSu/QuanLyNhanSu/fonts/font-times-new-roman/times-new-roman-14.ttf", BaseFont.IDENTITY_H, true);
            Font font = new Font(timesNewRoman, 14, Font.NORMAL);
            pdfDoc.Open();

            // Thêm thông tin lương vào file PDF
            Paragraph para = new Paragraph("Thông tin lương của nhân viên", font);
            pdfDoc.Add(para);

            para = new Paragraph("Mã nhân viên: " + tblLuong.MaNV, font);
            pdfDoc.Add(para);

            para = new Paragraph("Tên nhân viên: " + tblLuong.tblThongTinNV.TenNV, font);
            pdfDoc.Add(para);

            para = new Paragraph("Hệ số lương: " + tblLuong.tblHSL.HSL.ToString(), font);

QuanLyNhanSu/Views/QLLuongs/ChiTietLuong.cshtml
@model QuanLyNhanSu.Models.tblLuong
@{
    ViewBag.Title = "ChiTietLuong";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2 class="headerh2">Chi tiết lương tháng @Html.DisplayFor(model => model.Thang)</h2>
<div class="d-flex justify-content-center">
    <div class="w-25">
        <div class="d-flex">
            <p class="w-50">@Html.DisplayNameFor(model => model.tblThongTinNV.TenNV)</p>
            <p>@Html.DisplayFor(model => model.tblThongTinNV.TenNV)</p>
        </div>
        <div class="d-flex">
            <p class="w-50">
                Tiền thưởng
            </p>
            @Html.DisplayFor(model => model.tblThuong.TienThuong)
        </div>
        <div class="d-flex">
            <p class="w-50">
                Tiền phụ cấp
            </p>
            @Html.DisplayFor(model => model.tblPhuCap.TienPhuCap)
        </div>
        <div class="d-flex">
            <p class="w-50">
                Số ngày làm việc
            </p>

            @Html.DisplayFor(model => model.SoNgayLamViec)
        </div>
        <div class="d-flex">
            <p class="w-50">
                Số giờ làm việc
            </p>
            @Html.DisplayFor(model => model.SoGioLamViec)
        </div>
        <div class="d-flex">

            <p class="w-50">
                Tiền phạt
            </p>
            @Html.DisplayFor(model => model.TienPhat)

        </div>
        <div class="d-flex">
            <p class="w-50">
                Tạm ứng
            </p>


            @Html.DisplayFor(model => model.TamUng)
        </div>
        <div class="d-flex">
            <p class="w-50">
                Tổng lương
            </p>
            @Model.TongLuong()
        </div>
        <div class="d-flex">
            <button onclick="location.href='@Url.Action("DownloadPDF", "QLLuongs", new { id = Model.MaLuong })'" class="btn btn-success">Tải file PDF</button> &nbsp;
            <button onclick="location.href='@Url.Action("LuongNV", "QLLuongs", new { id = Model.MaLuong })'" class="btn btn-primary">Quay lại</button>
        </div>
    </div>
</div>

QuanLyNhanSu/Views/QLLuongs/Create.cshtml
@model QuanLyNhanSu.Models.tblLuong

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Thêm mới lương</h2>

@using (Html.BeginForm("Create","QLLuongs",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal px-md-5">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Mã lương
            <div class="col-md-5">
                @Html.EditorFor(model => model.MaLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Tháng
            <div class="col-md-5">
                @Html.EditorFor(model => model.Thang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Tên nhân viên
            <div class="col-md-5">
                @Html.DropDownList("MaNV", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Số ngày làm việc
            <div class="col-md-5">
                @Html.EditorFor(model => model.SoNgayLamViec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoNgayLamViec, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Số giờ làm việc
            <div class="col-md-5">
                @Html.EditorFor(model => model.SoGioLamViec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoGioLamViec, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Hệ số lương
            <div class="col-md-5">
                @Html.DropDownList("MaHSL", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaHSL, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            Thưởng
            <div class="col-md-5">
                @Html.DropDownList("MaThuong", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaThuong, "", new { @class = "text-danger" })
            </div>
        </div>
            
        <div class="form-group">
            Phụ cấp
            <div class="col-md-5">
                @Html.DropDownList("MaPhuCap", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPhuCap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Tiền phạt
            <div class="col-md-5">
                @Html.EditorFor(model => model.TienPhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TienPhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Tạm ứng
            <div class="col-md-5">
                @Html.EditorFor(model => model.TamUng, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TamUng, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group pt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu lại" class="btn btn-success" />
                @Html.ActionLink("Quay lại", "Index",null,new { @class="btn btn-primary"})
            </div>
        </div>
    </div>
}

QuanLyNhanSu/Views/QLLuongs/Delete.cshtml
@model QuanLyNhanSu.Models.tblLuong

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Xóa</h2>


<div class="d-flex justify-content-center">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tblThongTinNV.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblThongTinNV.TenNV)
        </dd>

        <dt>
            Mã thưởng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblThuong.MaThuong)
        </dd>

        <dt>
            Tháng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thang)
        </dd>

        <dt>
            Số ngày làm việc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoNgayLamViec)
        </dd>

        <dt>
            Số giờ làm việc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoGioLamViec)
        </dd>
        <dt>
            Tiền phạt
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TienPhat)
        </dd>

        <dt>
            Tạm ứng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TamUng)
        </dd>

    </dl>
</div>
<div class="d-flex justify-content-center">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xác nhân xóa" class="btn btn-danger" /> &nbsp;
            @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-success" })
        </div>
    }
</div>

QuanLyNhanSu/Views/QLLuongs/Details.cshtml
@model QuanLyNhanSu.Models.tblLuong

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Chi tiết lương tháng @Html.DisplayFor(model => model.Thang)</h2>
<div class="d-flex justify-content-center">
    <div class="w-25">
        <div class="d-flex">
            <p class="w-50">@Html.DisplayNameFor(model => model.tblThongTinNV.TenNV)</p>
            <p>@Html.DisplayFor(model => model.tblThongTinNV.TenNV)</p>
        </div>
        <div class="d-flex">
            <p class="w-50">
                Tiền thưởng
            </p>
            @Html.DisplayFor(model => model.tblThuong.TienThuong)
        </div>
        <div class="d-flex">
            <p class="w-50">
                Tiền phụ cấp
            </p>
            @Html.DisplayFor(model => model.tblPhuCap.TienPhuCap)
        </div>
        <div class="d-flex">
            <p class="w-50">
                Số ngày làm việc
            </p>

            @Html.DisplayFor(model => model.SoNgayLamViec)
        </div>
        <div class="d-flex">
            <p class="w-50">
                Số giờ làm việc
            </p>
            @Html.DisplayFor(model => model.SoGioLamViec)
        </div>
        <div class="d-flex">

            <p class="w-50">
                Tiền phạt
            </p>
            @Html.DisplayFor(model => model.TienPhat)

        </div>
        <div class="d-flex">
            <p class="w-50">
                Tạm ứng
            </p>


            @Html.DisplayFor(model => model.TamUng)
        </div>
        <div class="d-flex">
            <p class="w-50">
                Tổng lương
            </p>
            @Model.TongLuong()
        </div>
    </div>
</div>

<div class="d-flex justify-content-center">
    <p>
        @Html.ActionLink("Sửa", "Edit", new { id = Model.MaLuong }, new { @class = "btn btn-success" }) &nbsp;
        <button onclick="location.href='@Url.Action("DownloadPDF", "QLLuongs", new { id = Model.MaLuong })'" class="btn btn-success">Tải file PDF</button> &nbsp;
        @Html.ActionLink("Xóa", "Delete", null, new { id = Model.MaLuong }, new { @class = "btn btn-danger" }) &nbsp;
        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" }) &nbsp;
    </p>
</div>

QuanLyNhanSu/Views/QLLuongs/Edit.cshtml
@model QuanLyNhanSu.Models.tblLuong

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Chỉnh sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal px-md-4">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaLuong)

        <div class="form-group d-flex pb-2">
            <div class="control-label col-md-2"><p>Tháng</p></div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.Thang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pb-2">
            <div class="control-label col-md-2"><p>Họ và tên</p></div>
            <div class="col-md-5 ">
                @Html.DropDownList("MaNV", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pb-2">
            <div class="control-label col-md-2"><p>Số ngày làm việc</p></div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.SoNgayLamViec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoNgayLamViec, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pb-2">
            <div class="control-label col-md-2"><p>Số giờ làm việc</p></div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.SoGioLamViec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoGioLamViec, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pb-2">
            <div class="control-label col-md-2"><p>Hệ số lương</p></div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.tblHSL.HSL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tblHSL.HSL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pb-2">
            <div class="control-label col-md-2"><p>Tiền thưởng</p></div>
            <div class="col-md-5">
                @Html.DropDownList("MaThuong", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaThuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pb-2">
            <div class="control-label col-md-2"><p>Tiền phụ cấp</p></div>
            <div class="col-md-5">
                @Html.DropDownList("MaPhuCap", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPhuCap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pb-2">
            <div class="control-label col-md-2"><p>Tiền phạt</p></div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.TienPhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TienPhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex pb-2">
            <div class="control-label col-md-2"><p>Tạm ứng</p></div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.TamUng, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TamUng, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group  d-flex pt-2">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu lại" class="btn btn-success" />
            </div>
            <div>
                @Html.ActionLink("Quay lại danh sách", "Index",null,new { @class="btn btn-success"})
            </div>
        </div>
    </div>
}

QuanLyNhanSu/Views/QLLuongs/Index.cshtml
@model PagedList.IPagedList<QuanLyNhanSu.Models.tblLuong>
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headerh2">Danh sách lương nhân viên</h2>

<p class="px-md-5">
    @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-success" })
</p>
<form asp-action="Index" method="get" class="form-inline px-md-5 pt-2 d-flex justify-content-center" style="width:50%">
    <input class="form-control" name="searchName" placeholder="Nhập tên nhân viên..." type="text">
    @Html.DropDownList("searchMonth", new SelectList(Enumerable.Range(1, 12)), "Chọn tháng", new { @class = "form-control form-control-sm w-auto text-center" })
    <button class="btn btn-primary px-2" type="submit">
        <i class="fas fa-search"></i>
    </button>
</form>

<div class="px-md-5 pt-2">
    @using (Html.BeginForm("ExportToExcel", "QLLuongs", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    <div class="d-flex">
        @Html.DropDownList("month", new SelectList(Enumerable.Range(1, 12)), "Chọn tháng", new { @class = "form-control form-control-sm w-auto text-center" })
        <div>
            <input type="submit" value="Xuất file" class="btn-primary" />
        </div>
    </div>
        
    }
</div>
<form class="px-md-5">
    <table class="table">
        <tr class="">
            <th>Mã nhân viên</th>
            <th>
                Tên nhân viên
            </th>
            <th>
                Tháng
            </th>
            <th>
                Số ngày làm việc
            </th>
            <th>
                Hệ số lương
            </th>
            <th>
                Tạm ứng
            </th>
            <th>
                <a>Tổng lương</a>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblThongTinNV.TenNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Thang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoNgayLamViec)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblHSL.HSL)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TamUng)
                </td>
                <td>
                    @item.TongLuong()
                </td>
                <td>
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.MaLuong })
                </td>
            </tr>
        }
    </table>
</form>
<div class="pagination px-md-5 pt-2">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, @class = "pagination" }))
</div>

QuanLyNhanSu/Views/QLLuongs/LuongNV.cshtml
@model List<QuanLyNhanSu.Models.tblLuong>

@{
    ViewBag.Title = "LuongNV";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2 class="headerh2">Lương nhân viên @Session["TenNV"]</h2>
<form class="px-md-5">
    <table class="table">
        <tr class="">
            <th>
                Tháng
            </th>
            <th>
                Số ngày làm việc
            </th>
            <th>
                Hệ số lương
            </th>
            <th>
                Tạm ứng
            </th>
            <th>
                <a>Tổng lương</a>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Thang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoNgayLamViec)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblHSL.HSL)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TamUng)
                </td>
                <td>
                    @item.TongLuong()
                </td>
                <td>
                    @Html.ActionLink("Chi tiết", "ChiTietLuong", new { id = item.MaLuong })
                </td>
            </tr>
         }
    </table>
</form>